name: currency_text_input_formatter
description: Currency Text Input Formatter for Flutter. Use it easy and simple for your flutter app.
version: 2.1.11
homepage: https://github.com/gtgalone/currency_text_input_formatter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
